---

- name: Install xvfb
  apt: name=xvfb state=present

- name: Add google-chrome apt key
  apt_key:
    url:   "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add google-chrome apt repo to sources list
  copy: 
    src:  google-chrome.list
    dest: /etc/apt/sources.list.d/google-chrome.list
    mode: 0644
  register: repo

- name: Update apt repo cache for google-chrome
  apt:  update_cache=yes
  when: repo|changed

- name: Install google-chrome
  apt: name=google-chrome-stable state=present

- name: Download google-chrome driver archive
  get_url: 
    url:  "http://chromedriver.storage.googleapis.com/{{ jenkins_google_chrome_driver_version }}/chromedriver_linux64.zip"
    dest: /tmp/chromedriver_linux64.zip

- name: Decompress google-chrome driver archive
  unarchive:
    src:  /tmp/chromedriver_linux64.zip
    dest: /usr/local/share/
    mode: 0755
    copy: no

- name: Install google-chrome driver
  file:
    src:   /usr/local/share/chromedriver
    dest:  /usr/bin/chromedriver
    state: link

#- name: Ensure google-chrome sources list file auto-generated by package is removed to avoid duplicate conflict
#  file: path=/etc/apt/sources.list.d/google-chrome.list state=absent
