---

- name: Install xvfb
  apt: name=xvfb state=present

- name: Add google-chrome apt key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add google-chrome apt repo to sources list
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' update_cache=yes state=present

- name: Install google-chrome
  apt: name=google-chrome-stable state=present

- name: Download google-chrome driver archive
  get_url: url="http://chromedriver.storage.googleapis.com/{{ jenkins_google_chrome_driver_version }}/chromedriver_linux64.zip" dest=/tmp/chromedriver_linux64.zip

- name: Decompress google-chrome driver archive
  unarchive: src=/tmp/chromedriver_linux64.zip dest=/usr/local/share/ mode=0755 copy=no

- name: Install google-chrome driver
  file: path=/usr/local/share/chromedriver dest=/usr/bin/chromedriver state=link
