---

- include: "{{ jenkins_role|default('master') }}.yml"

- debug: var=jenkins_role

- name: Install jenkins-cli
  include: cli.yml
  when: jenkins_role == 'master'

- include: users.yml
  when: jenkins_role == 'master'

#- name: google-chrome-install
#  include: google-chrome.yml
#  when: jenkins_google_chrome_install
