---

- name: Add jenkins-ci apt key
  apt_key:
    url:   "http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key"
    state: present

- name: Add jenkins-ci apt repo to sources.list
  apt_repository: 
    repo:         "deb http://pkg.jenkins-ci.org/debian-stable binary/" 
    update_cache: yes
    state: present

- name: Install jenkins 
  apt:
    name:  "jenkins={{ jenkins_version|default('*') }}"
    state: present
  register: install

- name: Check jenkins home dir exists in case it is different from the default /var/lib/jenkins
  stat:
    path: "{{ jenkins_home }}"
  register: h

- name: Wait for jenkins initial admin password file to be created
  wait_for: 
    path: "/var/lib/jenkins/secrets/initialAdminPassword"
  when: not h.stat.isdir|default(false) and install|changed

- name: Stop jenkins
  service: name=jenkins state=stopped
  when: not h.stat.isdir|default(false)

- name: Stop processes running as jenkins user
  shell: pkill -u jenkins || true
  when: not h.stat.isdir|default(false)

- name: Ensure jenkins user home directory is in the appropriate location
  user:
    name:  "{{ jenkins_user }}"
    home:  "{{ jenkins_home }}"
    move_home: yes
  when: not h.stat.isdir|default(false)

- name: Create jenkins plugins directory
  file: 
    path:  "{{ jenkins_plugins_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
    state: directory 

- name: Install jenkins plugins
  get_url: 
    url:   "{{ jenkins_update_center_download_url }}/plugins/{{ item.split(':')[0] }}/{{ item.split(':')[1]|default('latest') }}/{{ item.split(':')[0] }}.hpi" 
    dest:  "{{ jenkins_plugins_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0644
  with_items: "{{ jenkins_plugins | unique }}"
  when: jenkins_update_plugins
  notify: Restart jenkins

- name: Create jenkins startup script default config
  template: 
    src:   etc.default.jenkins.j2
    dest:  /etc/default/jenkins
    owner: root 
    group: root 
    mode:  0644
  notify: Restart jenkins

- name: Start jenkins
  service: name=jenkins enabled=yes state=started

