---

- name: Install jenkins prerequisite packages
  apt:
    name:  "{{ item }}"
    state: present
  with_items: "{{ jenkins_prereq_pkgs|union(jenkins_apt_pkgs_extra) }}"

- name: Install extra pip packages desired
  pip:
    name:  "{{ item }}"
    state: present
  with_items: "{{ jenkins_pip_pkgs_extra }}"

##  WARNING: As of 20/03/16, Jenkins apt repo got broken. Only the latest 
##           version happens to be present. Older versions are missing. See
##           issues raised 
##              * https://issues.jenkins-ci.org/browse/JENKINS-33285
##              * https://issues.jenkins-ci.org/browse/INFRA-77
#
# This task is a hack to allow installing v1.x version of Jenkins. So remove once apt repo is fixed.
- name: Set jenkins apt repo prefix
  set_fact: _repo_prefix='-stable'
  when: jenkins_version|string|search('^1.6.*')

- name: Add jenkins-ci apt key
  apt_key:
    url:   "http://pkg.jenkins-ci.org/debian{{ _repo_prefix|default('') }}/jenkins-ci.org.key"
    state: present

- name: Add jenkins-ci apt repo to sources.list
  apt_repository: 
    repo:         "deb http://pkg.jenkins-ci.org/debian{{ _repo_prefix|default('') }} binary/" 
    update_cache: yes
    state: present

- name: Install jenkins 
  apt:
    name:  "jenkins={{ jenkins_version|default('*') }}"
    state: present

- name: Check jenkins home dir exists in case it is different from the default /var/lib/jenkins
  stat:
    path: "{{ jenkins_home }}"
  register: h

- name: Stop jenkins
  service: name=jenkins state=stopped
  when: not h.stat.isdir|default(false)

- name: Stop processes running as jenkins user
  shell: pkill -u jenkins || true
  when: not h.stat.isdir|default(false)

- name: Ensure jenkins user home directory is in the appropriate location
  user:
    name:  "{{ jenkins_user }}"
    home:  "{{ jenkins_home }}"
    move_home: yes
  when: not h.stat.isdir|default(false)

- name: Create jenkins plugins directory
  file: 
    path:  "{{ jenkins_plugins_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
    state: directory 

- name: Install jenkins plugins
  get_url: 
    url:   "{{ jenkins_update_center_download_url }}/plugins/{{ item.split(':')[0] }}/{{ item.split(':')[1]|default('latest') }}/{{ item.split(':')[0] }}.hpi" 
    dest:  "{{ jenkins_plugins_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0644
  with_items: "{{ jenkins_plugins | unique }}"
  when: jenkins_update_plugins
  notify: Restart jenkins

- name: Create jenkins startup script default config
  template: 
    src:   etc.default.jenkins.j2
    dest:  /etc/default/jenkins
    owner: root 
    group: root 
    mode:  0644
  notify: Restart jenkins
  
- name: Start jenkins
  service: name=jenkins state=started
